### ISSUE TITLE
ssgeneral stylesheet should be ssgeneral.css

### ISSUE THREAD

**Issue by robertlugg** [campbellluggblackwell/campbellluggblackwell.com#24]
Change the following files:
```html
WhoCameWhen.html:    <link rel="stylesheet" href="ssgeneral">
subscribe.html:    <link rel="stylesheet" href="ssgeneral">
volunteer.html:    <link rel="stylesheet" href="ssgeneral">
volunteer_test.html:    <link rel="stylesheet" href="ssgeneral">
```

to href `ssgeneral.css`

**Comment by JFernando122** [comment]
can i do it?
One thing is that i saw that the `volunteer_test.html` is at `old_rootsweb_website/` and not at `website/`, should i change it anyways

**Comment by robertlugg** [comment]
Its OK.  Thank you.  We are in the process of migrating from the "old_rootsweb_website" to the new "website", but I know there is a continuous flow of improvements we should make.
