### ISSUE TITLE
Sync from Bluehost to Github instead

### ISSUE THREAD

**Issue by robertlugg** [campbellluggblackwell/campbellluggblackwell.com#40]
To make management easier in the short term, switch the way we integrate website changes.  Query Bluehost periodically and upload changes to github.

**Comment by ThompsonShapiro** [comment]
The whole problem is that I can't push.to GitHub. That's why I started
using BlueHost's File Manager as a workaround. ZOOM would be the easiest
way to show you.

**Comment by robertlugg** [comment]
Set up github action to get the bluehost website (the static files) and upload them into the 'incoming' branch.  At the moment, it does this every hour.
